name: Echo message to push name

on: 
  push:
    branches: [ "main" ]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    env:
      NAME: "Juan" 
    steps:
      - name: Echo Step 1
        run: echo "🎉 New commit detected on the main branch! $NAME"
      
      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4
        with:
          

      - name: working dir after action
        run: ls -al

      - name: mensaje
        id: mensajestep
        run: echo "myvariable=holamundo" >> $GITHUB_OUTPUT

      - name: obtener mensaje
        run: echo " ${{ steps.mensajestep.outputs.myvariable }}"

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }} 
    needs: echo-job
    runs-on: ubuntu-latest

    steps:
      - name: Hola mundo2
        run: echo "Hola Mundo ${{ github.ref }}"        
