name: Echo message to push name

on: 
  push:
    branches: [ "main" ]

jobs:



  echo-job:
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.mensajestep.outputs.myvariable }}

    env:
      NAME: "Juan" 

    steps:
      - name: Echo Step 1
        run: echo "🎉 New commit detected on the main branch! $NAME"

      - name: Generar archivo
        run: 
          echo "Archivo de prueba" >> test.log

      - name: subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: test.log

      - name: mensaje
        id: mensajestep
        run: echo "myvariable=holamundo" >> $GITHUB_OUTPUT

      - name: obtener mensaje
        run: echo " ${{ steps.mensajestep.outputs.myvariable }}"

      - name: Working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4
        
      - name: working dir after action
        run: ls -al

  second-job:
    if: ${{ github.ref == 'refs/heads/main' }} 
    needs: echo-job
    runs-on: ubuntu-latest

    env:
      salida: ${{ steps.mensajestep.outputs.myvariable }}

    steps:
      - name: Hola mundo2
        run: echo "Hola Mundo ${{ github.ref }}"        
